/**
 * Browser stand-in for `node:crypto`, aliased in vite.config.ts.
 *
 * @ccguk/domain is a pure package but three modules (evidence/hash, esign/otp, esign/certificate) import
 * node:crypto for SHA-256 / HMAC. The web app never calls those functions (hashes for guided capture use
 * Web Crypto `crypto.subtle.digest`; OTPs are generated by the API), but Rollup must still bind the named
 * imports to bundle the rest of the domain package (formatGBP, registration helpers, clock definitions…).
 *
 * Every export throws if it is actually invoked, so a wrong import surfaces immediately in the browser.
 */
function unavailable(name: string): never {
  throw new Error(`node:crypto.${name} is not available in the browser. Use crypto.subtle (Web Crypto) or call the API.`);
}

export function createHash(_algorithm: string): never {
  return unavailable('createHash');
}
export function createHmac(_algorithm: string, _key: unknown): never {
  return unavailable('createHmac');
}
export function timingSafeEqual(_a: unknown, _b: unknown): never {
  return unavailable('timingSafeEqual');
}
export function randomBytes(_size: number): never {
  return unavailable('randomBytes');
}
export function randomUUID(): string {
  return globalThis.crypto.randomUUID();
}
export default { createHash, createHmac, timingSafeEqual, randomBytes, randomUUID };
